# this file specifies physical joint limits for in a special ros2 structure (acessed in diy_robotarm_macro.xacro and ros2 control i.e. moveit)

#NOTE: can be modified for the specific scene or task on user-properties, but look at the clearance of cabels!
#NOTE: specifing the joint_limits clrrectly has mayor influence on motion planning (search avoid breaks spaces),
#       self collisons doesn't need to be taken into account by specifying these paremeters

joint_limits:
  arm_shoulder:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 8.6
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_position: 3.14
    max_velocity: 1.04
    min_position: -3.14
    max_effort: 15  #in Nm

  arm_upper_arm:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 8.6
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_position: 3.14
    max_velocity: 1.04
    min_position: -3.14
    max_effort: 15


  arm_forearm:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 8.6
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_position: 3.14
    max_velocity: 1.04
    min_position: -3.14
    max_effort: 15


  arm_wrist_1:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 8.6
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_position: 3.14
    max_velocity: 1.04
    min_position: -3.14
    max_effort: 10

  arm_wrist_2:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 8.6
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_position: 3.14
    max_velocity: 1.04
    min_position: -3.14
    max_effort: 10

  arm_wrist_3:
    # acceleration limits are not publicly available
    has_acceleration_limits: true
    max_acceleration: 8.6
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_position: 3.14
    max_velocity: 1.04
    min_position: -3.14
    max_effort: 10

